language: c

env:
  - global:
    - WARNINGS_ARE_ERRORS=1

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs
after_failure:
  "cat /home/travis/build/lukejharmon/fossilMEDUSA/fossilMEDUSA.Rcheck/00install.out"

notifications:
  email:
    on_success: change
    on_failure: change
